name: Latest blog post workflow
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest english blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update this repo's README with latest english blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "8"
          comment_tag_name: "BLOG-POST-EN-LIST"
          feed_list: "https://www.alexandre-hublau.com/en/posts/rss.xml"
      - name: Update this repo's README with latest french blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "8"
          comment_tag_name: "BLOG-POST-FR-LIST"
          feed_list: "https://www.alexandre-hublau.com/fr/posts/rss.xml"
